dist: xenial

language: php

php:
  - '5.6'
  - '7.0'
  - '7.2'
  - '7.3'
  - '7.4'
  - 'nightly'


matrix:
  allow_failures:
    - php: 'nightly'


before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction --prefer-dist --dev

script:

  # PSR-2
  - ./vendor/bin/phpcs --standard=psr2 -n src/

  # PhpUnit
  - mkdir -p build/logs && ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
